@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault

package com.xiaoyue.celestial_enchantments.content.transfusion;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;